import assert from "node:assert/strict";
import test from "node:test";
import {
  buildPlanFilename,
  buildPlanMarkdown,
  normalizePlanDirectory,
  planTitleFromPrompt,
} from "../src/planFiles";

test("keeps plan storage inside a normalized workspace-relative directory", () => {
  assert.equal(normalizePlanDirectory(""), ".puneet/plans");
  assert.equal(normalizePlanDirectory("./notes\\plans/"), "notes/plans");
  assert.throws(() => normalizePlanDirectory("../plans"), /relative path/);
  assert.throws(() => normalizePlanDirectory("/tmp/plans"), /relative path/);
  assert.throws(() => normalizePlanDirectory("C:\\plans"), /relative path/);
});

test("builds readable, collision-resistant Markdown filenames", () => {
  assert.equal(
    buildPlanFilename(
      "Improve the login flow without changing the API",
      "item_ABC-12345678",
      new Date("2026-07-24T10:20:30.000Z"),
    ),
    "20260724T102030Z-improve-the-login-flow-without-changing-the-api-12345678.md",
  );
});

test("creates a concise title and complete Markdown document", () => {
  assert.equal(planTitleFromPrompt("## Refactor the billing worker\nwith context"), "Refactor the billing worker");
  assert.equal(
    buildPlanMarkdown(
      "Refactor the billing worker",
      "1. Inspect the queue.\n2. Update the worker.",
      new Date("2026-07-24T10:20:30.000Z"),
      "thread_123",
    ),
    [
      "# Refactor the billing worker",
      "",
      "_Generated by Puneet 3.0 on 2026-07-24T10:20:30.000Z. Codex chat: `thread_123`._",
      "",
      "1. Inspect the queue.",
      "2. Update the worker.",
      "",
    ].join("\n"),
  );
});
