import assert from "node:assert/strict";
import test from "node:test";
import {
  buildTadFilename,
  buildTadMarkdown,
  normalizeTadDirectory,
  tadTitleFromPrompt,
} from "../src/tadFiles";

test("keeps TAD storage inside a normalized workspace-relative directory", () => {
  assert.equal(normalizeTadDirectory(""), ".puneet/tads");
  assert.equal(normalizeTadDirectory("./docs\\architecture/"), "docs/architecture");
  assert.throws(() => normalizeTadDirectory("../tads"), /relative path/);
  assert.throws(() => normalizeTadDirectory("/tmp/tads"), /relative path/);
  assert.throws(() => normalizeTadDirectory("C:\\tads"), /relative path/);
});

test("builds readable, collision-resistant TAD filenames", () => {
  assert.equal(
    buildTadFilename(
      "Design the authentication refresh flow",
      "item_TAD-12345678",
      new Date("2026-07-24T10:20:30.000Z"),
    ),
    "20260724T102030Z-design-the-authentication-refresh-flow-12345678.md",
  );
});

test("preserves a skill-generated heading and adds generation metadata", () => {
  assert.equal(tadTitleFromPrompt("## Authentication refresh\nwith context"), "Authentication refresh");
  assert.equal(
    buildTadMarkdown(
      "Authentication refresh",
      "# Technical Architecture Document: Authentication refresh\n\n## Purpose\n\nRefresh tokens safely.",
      new Date("2026-07-24T10:20:30.000Z"),
      "thread_123",
    ),
    [
      "_Generated by Puneet 3.0 on 2026-07-24T10:20:30.000Z. Codex chat: `thread_123`._",
      "",
      "# Technical Architecture Document: Authentication refresh",
      "",
      "## Purpose",
      "",
      "Refresh tokens safely.",
      "",
    ].join("\n"),
  );
});
