export const DEFAULT_PLAN_DIRECTORY = ".puneet/plans";

export function normalizePlanDirectory(value: string): string {
  const normalized = value.trim().replaceAll("\\", "/").replace(/^\.\/+/, "").replace(/\/+/g, "/");
  if (!normalized) {
    return DEFAULT_PLAN_DIRECTORY;
  }
  if (
    normalized.startsWith("/") ||
    /^[A-Za-z]:\//.test(normalized) ||
    normalized.split("/").some((part) => part === "..")
  ) {
    throw new Error("The plan directory must be a relative path inside the active workspace.");
  }
  return normalized.replace(/\/$/, "") || DEFAULT_PLAN_DIRECTORY;
}

export function planTitleFromPrompt(prompt: string): string {
  const firstLine = prompt
    .split(/\r?\n/, 1)[0]
    ?.replace(/^#+\s*/, "")
    .replace(/\s+/g, " ")
    .trim();
  if (!firstLine) {
    return "Implementation plan";
  }
  return firstLine.length <= 80 ? firstLine : `${firstLine.slice(0, 79).trimEnd()}…`;
}

export function buildPlanFilename(prompt: string, itemId: string, generatedAt: Date): string {
  const timestamp = generatedAt.toISOString().replace(/[-:]/g, "").replace(/\.\d{3}Z$/, "Z");
  const slug = planTitleFromPrompt(prompt)
    .normalize("NFKD")
    .replace(/[^\p{Letter}\p{Number}]+/gu, "-")
    .replace(/^-+|-+$/g, "")
    .toLowerCase()
    .slice(0, 48)
    .replace(/-+$/g, "") || "implementation-plan";
  const suffix = itemId.replace(/[^A-Za-z0-9]/g, "").slice(-8).toLowerCase() || "plan";
  return `${timestamp}-${slug}-${suffix}.md`;
}

export function buildPlanMarkdown(
  prompt: string,
  plan: string,
  generatedAt: Date,
  threadId: string | null,
): string {
  const title = planTitleFromPrompt(prompt);
  const metadata = [
    `Generated by Puneet 3.0 on ${generatedAt.toISOString()}.`,
    threadId ? `Codex chat: \`${threadId}\`.` : "",
  ].filter(Boolean).join(" ");
  return `# ${title}\n\n_${metadata}_\n\n${plan.trim()}\n`;
}
