export const DEFAULT_TAD_DIRECTORY = ".puneet/tads";

export function normalizeTadDirectory(value: string): string {
  const normalized = value.trim().replaceAll("\\", "/").replace(/^\.\/+/, "").replace(/\/+/g, "/");
  if (!normalized) {
    return DEFAULT_TAD_DIRECTORY;
  }
  if (
    normalized.startsWith("/") ||
    /^[A-Za-z]:\//.test(normalized) ||
    normalized.split("/").some((part) => part === "..")
  ) {
    throw new Error("The TAD directory must be a relative path inside the active workspace.");
  }
  return normalized.replace(/\/$/, "") || DEFAULT_TAD_DIRECTORY;
}

export function tadTitleFromPrompt(prompt: string): string {
  const firstLine = prompt
    .split(/\r?\n/, 1)[0]
    ?.replace(/^#+\s*/, "")
    .replace(/\s+/g, " ")
    .trim();
  if (!firstLine) {
    return "Technical architecture";
  }
  return firstLine.length <= 80 ? firstLine : `${firstLine.slice(0, 79).trimEnd()}…`;
}

export function buildTadFilename(prompt: string, itemId: string, generatedAt: Date): string {
  const timestamp = generatedAt.toISOString().replace(/[-:]/g, "").replace(/\.\d{3}Z$/, "Z");
  const slug = tadTitleFromPrompt(prompt)
    .normalize("NFKD")
    .replace(/[^\p{Letter}\p{Number}]+/gu, "-")
    .replace(/^-+|-+$/g, "")
    .toLowerCase()
    .slice(0, 48)
    .replace(/-+$/g, "") || "technical-architecture";
  const suffix = itemId.replace(/[^A-Za-z0-9]/g, "").slice(-8).toLowerCase() || "tad";
  return `${timestamp}-${slug}-${suffix}.md`;
}

export function buildTadMarkdown(
  prompt: string,
  tad: string,
  generatedAt: Date,
  threadId: string | null,
): string {
  const title = tadTitleFromPrompt(prompt);
  const content = tad.trim();
  const metadata = [
    `Generated by Puneet 3.0 on ${generatedAt.toISOString()}.`,
    threadId ? `Codex chat: \`${threadId}\`.` : "",
  ].filter(Boolean).join(" ");
  const document = /^#\s+\S/m.test(content)
    ? content
    : `# Technical Architecture Document: ${title}\n\n${content}`;
  return `_${metadata}_\n\n${document}\n`;
}
